language: python
python:
  - 3.6
script:
  - make html
before_deploy:
  - cd build/html/
deploy:
  provider: pages
  file_glob: true
  file: build/html/*
  skip-cleanup: true
  github-token: $GH_TOKEN # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
